import type { CreatorRecord, OSDataState } from "@/lib/os-types";

function createId(prefix: string, seed: string) {
  return `${prefix}-${seed}`.toLowerCase().replace(/[^a-z0-9-]/g, "-");
}

const demoCreators: CreatorRecord[] = [
  {
    id: "creator-anna-west",
    platform: "TikTok",
    country: "US",
    niche: "Home Decor",
    keyword: "quiet luxury decor",
    creatorName: "Anna West Living",
    profileLink: "https://www.tiktok.com/@annawestliving",
    followers: "128000",
    averageViews: "62000",
    email: "anna@westliving.co",
    instagram: "@annawestliving",
    tiktok: "@annawestliving",
    youtube: "Anna West Living",
    facebook: "Anna West Home",
    notes: "Strong visual storytelling, high comment quality.",
  },
  {
    id: "creator-maya-studio",
    platform: "Instagram",
    country: "UAE",
    niche: "Lifestyle / Interiors",
    keyword: "minimal apartment setup",
    creatorName: "Maya Studio Journal",
    profileLink: "https://www.instagram.com/mayastudiojournal",
    followers: "86000",
    averageViews: "31000",
    email: "partnerships@mayastudiojournal.com",
    instagram: "@mayastudiojournal",
    tiktok: "@mayastudiojournal",
    youtube: "Maya Studio Journal",
    facebook: "Maya Studio Journal",
    notes: "Audience aligns with mid-high income interiors shoppers.",
  },
];

export function createDemoState(): OSDataState {
  const [first, second] = demoCreators;

  return {
    creators: demoCreators,
    audits: [
      {
        id: createId("audit", first.id),
        creatorId: first.id,
        creatorName: first.creatorName,
        contentMatchScore: "9/10",
        engagementScore: "8/10",
        audienceMatch: "High",
        commentQuality: "Real and purchase-intent comments",
        brandSafety: "Safe",
        pastSponsoredContent: "Yes - home brands, strong fit",
        finalGrade: "A",
        decision: "Contact",
      },
    ],
    outreach: [
      {
        id: createId("outreach", first.id),
        creatorId: first.id,
        creatorName: first.creatorName,
        contactChannel: "Email",
        firstContactDate: "2026-06-01",
        messageTemplate: "Warm intro + product value + affiliate upside",
        followUp1Date: "2026-06-04",
        followUp2Date: "2026-06-08",
        replyStatus: "Replied",
        collaborationInterest: "Interested in sample + affiliate",
        notes: "Requested neutral color options and quick shipping.",
      },
    ],
    collaborations: [
      {
        id: createId("collab", first.id),
        creatorId: first.id,
        creatorName: first.creatorName,
        collaborationType: "Affiliate",
        fee: "0",
        commissionRate: "15%",
        deliverables: "1 TikTok video + 2 IG stories",
        platform: "TikTok + Instagram",
        deadline: "2026-06-15",
        agreementStatus: "Confirmed",
      },
    ],
    samples: [
      {
        id: createId("sample", first.id),
        creatorId: first.id,
        creatorName: first.creatorName,
        productName: "Arc Mirror - S6 Nova",
        sku: "S6N-ARC-01",
        color: "Cream White",
        shippingAddress: "221B Baker Street, London",
        phone: "+44 20 7946 0958",
        country: "UK",
        logisticsProvider: "UPS",
        trackingNumber: "1Z9999999999999999",
        shippingStatus: "In Transit",
        deliveredDate: "",
      },
    ],
    contentTracking: [
      {
        id: createId("content", first.id),
        creatorId: first.id,
        creatorName: first.creatorName,
        contentBrief: "Bedroom makeover with quiet luxury mirror setup",
        scriptDirection: "Before/after + emotional lifestyle hook",
        keySellingPoints: "Premium finish, anti-fog coating, fast shipping",
        discountCode: "ANNA15",
        trackingLink: "https://brand.com/p/arc-mirror?utm_source=anna",
        plannedPostDate: "2026-06-18",
        actualPostDate: "",
        postLink: "",
        tagChecked: "Pending",
        linkChecked: "Pending",
      },
    ],
    performance: [
      {
        id: createId("perf", second.id),
        creatorId: second.id,
        creatorName: second.creatorName,
        views: "42800",
        likes: "2980",
        comments: "216",
        clicks: "1210",
        orders: "49",
        revenue: "7350",
        conversionRate: "4.05%",
        roi: "3.8x",
        finalResult: "Reuse",
      },
    ],
    contentMaterials: [
      {
        id: "mat-1",
        platform: "TikTok",
        topic: "Top 20 home decor hooks this week",
        format: "Hook list + visual breakdown",
        insight: "Strong performance from calm voice-over + POV opening.",
        status: "Ready",
      },
      {
        id: "mat-2",
        platform: "Instagram",
        topic: "Reels trend: apartment lighting transformation",
        format: "Before/after reel",
        insight: "High save rate when CTA asks users to rate setup 1-10.",
        status: "In Progress",
      },
    ],
    competitorContent: [
      {
        id: "comp-1",
        brand: "Brand A",
        platform: "TikTok",
        contentType: "Creator testimonial",
        hook: "I did not expect this mirror to change my room this much",
        cta: "Comment 'link' for details",
        notes: "Strong emotional hook in first 2 seconds.",
      },
      {
        id: "comp-2",
        brand: "Brand B",
        platform: "Instagram",
        contentType: "Room walkthrough",
        hook: "Quiet luxury bedroom in under $500",
        cta: "Tap profile for product list",
        notes: "Use of price framing increases click intent.",
      },
    ],
    contentCalendar: [
      {
        id: "cal-1",
        date: "2026-06-03",
        platform: "TikTok",
        campaign: "Mirror Summer Push",
        scriptTemplate: "POV Upgrade Story",
        owner: "You",
        status: "Planned",
      },
      {
        id: "cal-2",
        date: "2026-06-04",
        platform: "Instagram",
        campaign: "UGC Repurpose",
        scriptTemplate: "Before/After Reel",
        owner: "You",
        status: "Drafting",
      },
    ],
    scriptTemplates: [
      {
        id: "tpl-1",
        templateName: "POV Lifestyle Hook",
        scenario: "Creator short video",
        structure: "Hook -> Problem -> Product -> CTA",
        keyPrompt: "Focus on emotion + practical benefit in 25s",
        notes: "Best for TikTok native pacing.",
      },
      {
        id: "tpl-2",
        templateName: "Offer + Credibility Caption",
        scenario: "Instagram caption",
        structure: "Context -> Value -> Social Proof -> CTA",
        keyPrompt: "Keep tone premium and concise.",
        notes: "Use for carousel and reels.",
      },
    ],
    ecommerceTracking: [
      {
        id: "eco-1",
        productName: "Arc Mirror - S6 Nova",
        productPageUrl: "https://brand.com/p/arc-mirror",
        creatorName: first.creatorName,
        trackingLink: "https://brand.com/p/arc-mirror?utm_source=anna",
        discountCode: "ANNA15",
        utmSource: "tiktok_anna_west",
        clicks: "1210",
        orders: "49",
        revenue: "7350",
        conversionRate: "4.05%",
      },
      {
        id: "eco-2",
        productName: "Aura Wall Art - Set 3",
        productPageUrl: "https://brand.com/p/aura-wall-art",
        creatorName: second.creatorName,
        trackingLink: "https://brand.com/p/aura-wall-art?utm_source=maya",
        discountCode: "MAYA10",
        utmSource: "instagram_maya_studio",
        clicks: "760",
        orders: "22",
        revenue: "3280",
        conversionRate: "2.89%",
      },
    ],
  };
}
